version: "3.8"

services:
  todo.api:
    image: todoapi:dev
    build:
      context: .
      dockerfile: ApiToDo/Dockerfile
    ports:
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - todo-network
    depends_on:
      - mssql-server
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "numsey#2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - todo-network
    volumes:
      - C:/dados/volumes/sqlserver:/var/opt/mssql/data

networks:
  todo-network:
    driver: bridge
